### ISSUE TITLE
Provide ability to set own OkHttp implementation

### ISSUE THREAD

**Issue by mattmook** [babylonhealth/certificate-transparency-android#6]
As per comments in https://github.com/square/okhttp/issues/2938, provide clients the ability to use their own OkHttp client. This would allow, amongst other things, for proxy server settings to be set etc.

**Comment by yschimke** [comment]
This would even be great to allow replacing out retrofit, looking at the interface it would be trivial to implement without retrofit, however the internal classes like LogListDataSourceFactory make it impossible to reuse parts of the code without rewriting from scratch.

I'm stuck because I want to use this in graal but retrofit is a blocker here, and I don't want to rewrite the library from scratch.  Maybe LogListService is a better point to allow alternative implementations.

```
internal interface LogListService {
    @GET("log_list.json")
    @Headers("Cache-Control: no-cache", "Max-Size: 1048576")
    suspend fun getLogList(): ByteArray

    @GET("log_list.sig")
    @Headers("Cache-Control: no-cache", "Max-Size: 512")
    suspend fun getLogListSignature(): ByteArray

    @GET("log_list.zip")
    @Headers("Cache-Control: no-cache", "Max-Size: 2097152")
    suspend fun getLogListZip(): ByteArray
}
```

**Comment by mattmook** [comment]
The next release will allow the overriding of OkHttp or indeed implementing your own LogListService. It also removes the use of Retrofit.
